version: 2

jobs:

  test:

    docker:

      - image: edbizarro/gitlab-ci-pipeline-php:7.2

    working_directory: /var/www/html

    steps:

      - checkout

      - run: composer install --no-interaction --no-progress   

      - run: touch storage/test.sqlite

      - run: php artisan migrate --seed --env=testing --force

      - run: mkdir -p tests/_output

      - run: vendor/bin/phpunit --log-junit tests/_output/junit.xml
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output


workflows:

  version: 2 

  deploy:

    jobs:

      - test